### ISSUE TITLE
Remove text when spinner is present

### ISSUE THREAD

**Issue by jgentes** [yury-dymov/react-bootstrap-button-loader#1]
Hi, thanks for creating this loader button - it's great!

Just wanted to mention that when I use it, I remove the text when the spinner is present. I personally like that approach vs. moving the text to the side when it's active. The only thing I have to consider is the width of the button. It would be nice if this were somehow built into the module with an option. Here's an example of how I use it (grey-spinner class modifies the color of the spinner graphic):
```
<Button bsStyle="default" loading={state == 'busy'} className="grey-spinner" style={{minWidth: '90px'}} onClick={() => this.props.dispatch(getLog())}>{state !== 'busy' ? 'View Log' : ''}</Button>
```

**Comment by yury-dymov** [comment]
Hi @jgentes,

First of all, thank you for the nice feedback. If I understood correctly, you want to hide the text but keep width of the button. Currently, I am not able to check, what happens if button is in the loading state but there is no text as I will have my laptop back only next week. If it renders ugly, than it is a bug obviously. If everything is fine but you want a different behavior, I would recommend to define your own component based on this one, which overrides custom behavior in a way you want.

**Comment by jgentes** [comment]
I was able to get it work perfectly by just specifying the minimum width of
the button. Then when the text disappears and the spinner appears, there's
no change to the button width. I was just thinking that if there's a more
programmatic way to do it, that would be nice.

Thanks again!

**Comment by yury-dymov** [comment]
Hello @jgentes, finally got my laptop back.

Give me couple of days to think, what can be done to implement this feature without evaluating width during runtime or doing something strange

**Comment by yury-dymov** [comment]
Oh, completely forgot about this one. I would say it works fine for me and I don't face such use-case, so I am not going to implement it but PRs are welcome :)
